### ISSUE TITLE
clarify synopsys

### ISSUE THREAD

**Issue by KES777** [Grinnz/Role-EventEmitter#1]
if `Role::EventEmitter` is `Role::Tiny` it would be better to use it in SYNOPSIS.

current example:

```
package Channel;
use Moo;
with 'Role::EventEmitter';
```
force me to think that I must to install `Moo` to use this module

**Comment by Grinnz** [comment]
Thanks. This was originally a Moo::Role.

**Comment by Grinnz** [comment]
https://github.com/Grinnz/Role-EventEmitter/commit/67c577b33bfd4cad952fa7e8946cbaf2365c6cd0
